DROP DATABASE IF EXISTS TATE;
CREATE DATABASE TATE;
USE TATE;

CREATE TABLE Artist
(
	ID INT,
	Name VARCHAR(128),
	Gender VARCHAR(6),
	Dates VARCHAR(100),
	YearOfBirth VARCHAR(4),
	YearOfDeath VARCHAR(4),
	PlaceOfBirth VARCHAR(64),
	PlaceOfDeath VARCHAR(64),
	url VARCHAR(256),

	PRIMARY KEY(ID)
);

CREATE TABLE Artwork
(
	ID INT NOT NULL AUTO_INCREMENT,
	AccessionNumber VARCHAR(7),
	Artist VARCHAR(128) NOT NULL,
	ArtistRole VARCHAR(32),
	ArtistId INT,
	Title VARCHAR(512) NOT NULL,
	DateText VARCHAR(128),
	Medium VARCHAR(128),
	CreditLine VARCHAR(1024),
	Year VARCHAR(8),
	AcquisitionYear VARCHAR(4),
	Dimensions VARCHAR(256),
	Width VARCHAR(11),
	Height VARCHAR(5),
	Depth VARCHAR(5),
	Units VARCHAR(2),
	Inscription VARCHAR(32),
	ThumbnailCopyright VARCHAR(1024),
	ThumbnailUrl VARCHAR(128),
	url VARCHAR(256),

	PRIMARY KEY(ID),
	FOREIGN KEY(ArtistId) REFERENCES Artist(ID)
		ON UPDATE CASCADE ON DELETE RESTRICT
);
